import argparse
import csv
import random
from pathlib import Path


def build_templates():
    billing = [
        "Why was my card charged after I cancelled yesterday?",
        "Invoice lists 60 seats but we only have 34 users.",
        "Please resend the receipt with our VAT ID included.",
        "Bank shows two identical charges for this renewal.",
        "Renewal price is higher than the contract we signed.",
        "Payment cleared yet the account still says overdue.",
        "A setup fee appeared even though we're existing customers.",
        "Need the invoice in CAD instead of USD for audit.",
        "Please split this invoice across two corporate cards.",
        "Promised credit from last month is missing.",
        "Billing portal times out when downloading invoices.",
        "Tax applied even after we uploaded exemption certificate.",
        "Charge descriptor on statement is incorrect for our books.",
        "Billed for add-ons that were never enabled.",
        "Nonprofit discount vanished on this cycle.",
        "Invoice number duplicates a prior document.",
        "Receipt PDF is missing our registered address.",
        "We need W-9 and bank info to release payment.",
        "Backdate the invoice to the service start date.",
        "Billing email must be ap@company.org, not mine.",
        "Billing cycle switched to annual without consent.",
        "Why is there a foreign transaction fee on this charge?",
        "Billed during the supposed free trial window.",
        "Proration after downgrade seems too high.",
        "Charge succeeded but access downgraded to free.",
        "Portal shows unpaid while Stripe shows paid.",
        "Late fee added even though we paid before due date.",
        "Need separate invoices for US and EU entities.",
        "Statement period overlaps last month's dates.",
        "Currency flipped from EUR to GBP without notice.",
        "Tax ID is misspelled on the PDF.",
        "Remove SMS overage fee; we stayed within quota.",
        "Need itemized lines for each user and add-on.",
        "Renewal date moved earlier; we lose service time.",
        "Invoice total doesn't match sales quote.",
        "Charge posted at 2 a.m. and flagged fraud alerts.",
        "Billing address edits never save in the portal.",
        "Refund the duplicate ACH from last night.",
        "We need quarterly billing, not monthly.",
        "Contract promised price lock; rate increased.",
        "Card on file expired; update flow keeps failing.",
        "Invoice download link returns 404.",
        "Cost center code missing on the invoice.",
        "Charged for sandbox environments we don't use.",
        "Tax rate is using the wrong state rules.",
        "Send both CSV and PDF copies of the invoice.",
        "Charged while the account was paused.",
        "Why are micro test charges still pending?",
        "Apply our credit memo before the next run.",
        "Totals include a processing fee not in our contract.",
        "Invoice shows annual term; we requested quarterly.",
    ]

    technical = [
        "Login spinner never finishes on the web app.",
        "Saving a draft crashes Android on Pixel 7.",
        "Dashboard stays blank in Chrome 123 until a hard refresh.",
        "CSV export downloads a file with only headers.",
        "Push alerts stopped after updating to iOS 17.4.",
        "Searching ticket IDs returns no matches.",
        "File uploads freeze at 68% then restart.",
        "Reports page times out with a 504 after 20 seconds.",
        "Login form loops back with no error message.",
        "Session drops every few minutes while typing.",
        "Assign button clicks but never assigns.",
        "Battery drain doubled after the latest release.",
        "Voice calls cut out after one minute on Wi-Fi.",
        "Chat widget will not open in Safari private windows.",
        "Export button missing in the analytics view.",
        "Settings page flashes JSON before rendering UI.",
        "Mobile keyboard covers the reply text box on iOS.",
        "Presence shows offline while connected.",
        "Article images fail to render on slow networks.",
        "API search returns 500 when filters are combined.",
        "Autosave randomly wipes my reply.",
        "Keyboard shortcuts stopped working on Windows.",
        "Captcha never loads on the login page.",
        "Status dropdown is empty when creating tickets.",
        "Tablet app refuses to rotate to landscape.",
        "Notifications arrive hours late or not at all.",
        "PDF exports show blank after page one.",
        "Attaching MOV files crashes the client.",
        "Attachment downloads stall at 0 bytes.",
        "New ticket modal spins forever after click.",
        "Inbox shows perpetual spinner on Firefox ESR.",
        "Dashboard charts show zero despite data in API.",
        "Today's tickets vanish until I refresh.",
        "Reply editor strips markdown formatting.",
        "VPN connections log me out instantly.",
        "Web app logs out if tab is backgrounded.",
        "Voice note playback never starts on desktop.",
        "Search filters reset after every query.",
        "Dark mode toggle vanished from preferences.",
        "Chat bubble overlaps the send button on mobile.",
        "Inline thumbnails show broken icons.",
        "API returns 429 even under light usage.",
        "Bulk select checkboxes don't toggle.",
        "Safari prompts a JSON download on login.",
        "Link previews stopped rendering inside tickets.",
        "Scheduled exports never arrive by email.",
        "Pinned filters disappear after refresh.",
        "macOS desktop app opens to a white window.",
        "Chrome requires cache clear to load new release.",
        "SAML login loops when third-party cookies blocked.",
        "Composer spellcheck underline hides text.",
        "Scrolling jumps back to top of ticket list.",
        "Inline code loses monospace font on send.",
        "Screen reader announces unlabeled buttons.",
        "Android push opens the wrong ticket thread.",
        "Download links return 403 for PDFs.",
        "Ticket merge spins forever without completing.",
        "CC field drops addresses after saving.",
        "Image paste creates duplicate attachments.",
        "Typing lags heavily after 200 characters.",
        "Status updates via API never reflect in UI.",
        "Mobile app caches old avatars and won't refresh.",
        "Email replies create duplicate tickets in queue.",
        "Outlook add-in fails to authenticate.",
        "Slack notifications fire twice per event.",
        "Kanban view shows empty columns until reload.",
        "Custom domain throws certificate warning.",
        "Time tracking widget resets mid-ticket.",
        "Autocomplete for tags shows stale options.",
        "Webhooks are delivered out of order.",
        "iOS app ignores system font scaling.",
        "Mentions don't ping the tagged agent.",
        "AI summary sometimes replaces my draft text.",
        "OneDrive attachments fail to upload.",
        "Mac app doesn't respect proxy settings.",
        "Pagination arrows disappear on small screens.",
        "CSV import rejects valid UTF-8 characters.",
        "Typing indicator shows the wrong agent name.",
        "Analytics date picker jumps back to 1970.",
        "Draft replies vanish after switching networks.",
        "Ticket history events appear out of order.",
    ]

    account = [
        "Locked out after too many attempts; please reset.",
        "Password reset email says token already used.",
        "SMS 2FA codes never arrive to my device.",
        "Switch my login email to the new corporate address.",
        "Account suspended without any warning.",
        "Need to merge two org accounts into one profile.",
        "Forgot my username; can't finish password reset.",
        "Verification loop keeps sending me back to login.",
        "Remove an old phone from trusted devices list.",
        "Lost admin role; now only have viewer access.",
        "Account deactivated while billing still charges us.",
        "Update the phone number that receives MFA codes.",
        "Invite flow says my email already exists elsewhere.",
        "Delete my account and all associated data.",
        "Pending verification email never arrives.",
        "Unlock my account flagged for suspicious login.",
        "Recovery email inbox is gone; need alternative proof.",
        "Login says account not found but I'm a paying user.",
        "Two-factor toggle errors every time I enable it.",
        "Invite link expired before I could accept it.",
        "Transfer workspace ownership to another admin.",
        "Login alert shows a country I've never visited.",
        "Reset security questions; I forgot the answers.",
        "Role changed from admin to agent unexpectedly.",
        "Team invite spinner never completes on mobile.",
        "Remove me from a former employer's workspace.",
        "Profile avatar upload fails silently.",
        "Need a list of active devices and sessions.",
        "Email on file is dead; need to change it.",
        "Captcha required on every login attempt.",
        "SMS codes arrive hours late or not at all.",
        "Temporarily disable MFA so I can get back in.",
        "Pages I used to access now deny permission.",
        "Company name on profile is incorrect.",
        "One-time code is sent to an old phone number.",
        "Password rules reject strong passwords I try.",
        "Timezone keeps reverting to UTC.",
        "SSO redirects in a loop after successful IdP login.",
        "Cannot remove a departed admin from the org.",
        "Multiple duplicate invites keep hitting my inbox.",
        "Created two profiles by accident; need merge.",
        "Require a full export of my account data.",
        "Email verification link returns token invalid.",
        "Display name reverts after saving changes.",
        "Lockout timer never counts down.",
        "Authenticator app lost codes; need reset.",
        "Forgot-password email never arrives.",
        "Consent screen shows on every login.",
        "Org list empty even though I'm invited.",
        "Updated terms button is disabled for me.",
        "Logged out immediately after passing MFA.",
        "Invite marked invalid right after sending.",
        "Primary email change is blocked with no reason.",
        "Login form rejects uppercase letters in email.",
        "Remove a stale workspace linked to my profile.",
        "Locked out after changing my email address.",
        "Profile name won't stick after editing.",
        "Account recovery form errors on submit.",
        "Need to rotate all API tokens for my user.",
        "Duplicate organizations appear under my profile.",
        "Can't revoke an old device in security settings.",
        "Need audit history of my logins for security.",
        "Never received backup codes after enabling MFA.",
        "Session ends whenever VPN reconnects.",
        "Prompted for captcha on every page in the app.",
        "SSO users need a backup password option.",
        "Need to change the country/region on my profile.",
        "Pending invites can't be cancelled.",
        "Notifications use the wrong timezone.",
    ]

    feature = [
        "Bulk close tickets older than 60 days with one click.",
        "Two-way sync with Jira Data Center and Cloud.",
        "Full dark theme plus high-contrast accessibility mode.",
        "Export tickets to JSONL, Parquet, and XLSX.",
        "Custom fields with regex validation and defaults.",
        "Shortcuts for assign, macro insert, and send.",
        "Weekly SLA breach digest grouped by queue.",
        "Filter by tag, assignee, priority together.",
        "Billing-only admin role separate from workspace admin.",
        "Quiet hours toggle to silence notifications.",
        "Ticket export API with incremental cursors.",
        "Schedule reports to Slack, Teams, and email.",
        "Custom branding for all outbound notifications.",
        "Mobile widget showing open tickets by priority.",
        "Save, share, and pin search views per team.",
        "Add Dutch and Korean localizations.",
        "Refund approval workflow with two approvers.",
        "Include inline images when exporting ticket history.",
        "Follow a ticket to receive internal updates.",
        "SAML JIT plus SCIM provisioning for users.",
        "Webhooks for SLA breached and approaching events.",
        "Priority queue view with live countdown timers.",
        "Bulk assign via round-robin by skill group.",
        "Detect and suggest merging duplicate tickets.",
        "Customizable dashboards with drag/drop cards.",
        "Response time percentile charts per queue.",
        "Auto-reminders when customer hasnot replied.",
        "Localized knowledge base with per-language URLs.",
        "Per-brand email templates and logos.",
        "Exportable audit log with IP and user agent.",
        "Sandbox environment mirroring production schema.",
        "Hover quick actions (assign/close/note) in list.",
        "Read-only compliance role with export rights.",
        "Pin critical tickets to the top of views.",
        "Custom SLA policies per customer or plan.",
        "CSV import mapping to custom fields and tags.",
        "Shift handoff summary for next support team.",
        "Webhooks only for comment-created events.",
        "Embedded public status page for end users.",
        "Teams adaptive card notifications with actions.",
        "On-call schedule with pager-style escalation.",
        "Upload custom notification sounds per user.",
        "Compact density mode for wide monitors.",
        "Custom ticket ID prefixes per brand/site.",
        "Round-robin assignment within time windows.",
        "In-app changelog drawer for new features.",
        "OAuth scopes limited to read-only analytics.",
        "RTL layout support for Arabic and Hebrew.",
        "Agent workload forecast for the next 7 days.",
        "GraphQL API alongside REST endpoints.",
        "AI reply suggestions that respect tone presets.",
        "Printable one-page ticket summary for audits.",
        "CSAT trends by customer segment over time.",
        "Mute a ticket thread without leaving the queue.",
        "Auto-tagging based on keywords and sentiment.",
        "Snooze tickets until a specific date/time.",
        "Multi-brand portal with custom domains.",
        "Role-based shared macro library.",
        "Attach voice notes directly in the ticket.",
        "Browser tab notifications for new assignments.",
        "Bulk status change with conditional rules.",
        "Customer portal search with synonyms support.",
        "Embedded video calls inside a ticket thread.",
    ]

    complaint = [
        "I've waited a week with no response from support.",
        "Service went down twice today during peak hours.",
        "Latest update broke the features we rely on.",
        "Support keeps closing my ticket without fixing it.",
        "UI changes every week and slows our workflow.",
        "Still getting promo emails after opting out.",
        "Phone agent was dismissive and rushed.",
        "Refund promised two weeks ago is still missing.",
        "Yesterday's outage cost us a client demo.",
        "Fourth time reporting this exact bug.",
        "Docs are outdated and contradict the product.",
        "Response times fall far short of your SLA.",
        "Upgrade made the platform unstable for us.",
        "Status page said green while we were offline.",
        "I'm tired of re-explaining to new agents.",
        "Billing support never answers or calls back.",
        "Had to chase three times for a basic update.",
        "Chat session ended without warning mid-issue.",
        "Overall support experience has been awful.",
        "Features change without notifying admins.",
        "Feels like no one reads the ticket details.",
        "Product doesn't match what sales promised.",
        "Replies sound canned and don't solve anything.",
        "Your fix introduced another bug that cost hours.",
        "Prices keep rising while quality drops.",
        "I keep getting bounced between teams.",
        "Platform is unreliable during traffic spikes.",
        "No straight answer on when you'll fix this.",
        "Constant updates disrupt our workflow.",
        "My urgent P1 was downgraded to normal.",
        "SLA claims feel like marketing fluff.",
        "Three follow-ups needed before anyone acts.",
        "Product quality has clearly regressed.",
        "Queue wait times are excessive every morning.",
        "Agents ask for info already in the ticket.",
        "Feels like we're beta testing unfinished features.",
        "Escalations disappear with no feedback.",
        "Knowledge base articles conflict with each other.",
        "Postmortems are vague and unhelpful.",
        "We're close to churning because trust is gone.",
        "Notifications spam us despite turning them off.",
        "Tickets marked resolved with nothing fixed.",
        "Features removed without warning.",
        "Support misses scheduled call-backs repeatedly.",
        "No credit offered after repeated downtime.",
        "Impossible to reach a manager to escalate.",
        "We lost customers due to your outages.",
        "I shouldn't have to beg for basic support.",
        "We feel de-prioritized after upgrading plans.",
        "Refund approvals take too long with no updates.",
        "Roadmap shifts with zero transparency.",
        "Security concerns get brushed off.",
        "You send surveys but ignore complaints.",
        "Chat disconnects mid-session frequently.",
        "Scripts ignore the context we provide.",
        "We re-open tickets because fixes don't stick.",
        "Fixes get rolled back without notice.",
        "No one owns the issue; constant hand-offs.",
        "Service slows to a crawl every evening.",
        "Release notes miss breaking changes.",
        "Collected logs for you; they were ignored.",
        "Incident alerts arrive hours late.",
        "Refund process is slow and opaque.",
        "Too much experimenting on our production data.",
        "This experience feels adversarial now.",
        "Mobile app crashes daily with no resolution.",
        "Support portal times out when adding comments.",
        "Escalation promised yesterday never came.",
        "Downtime alerts never reached our inbox.",
        "Six tickets merged incorrectly and lost detail.",
        "Compliance questions answered with canned text.",
        "Critical bugs keep returning after each release.",
        "Beta features were enabled without consent.",
        "No compensation for revenue lost in outage.",
        "Status page lags reality by hours.",
        "Help center links are broken throughout.",
        "Still no root cause for last month's outage.",
        "Support keeps asking for the same screenshots.",
    ]

    return {0: billing, 1: technical, 2: account, 3: feature, 4: complaint}


def load_existing_texts(out_path):
    if not out_path.exists():
        return set()
    existing = set()
    with out_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = (row.get("text") or "").strip()
            if text:
                existing.add(text)
    return existing


def generate_samples(existing_texts, shuffle, seed):
    templates = build_templates()
    rows = []
    for label, items in templates.items():
        for text in items:
            if text in existing_texts:
                continue
            rows.append((text, label))
            existing_texts.add(text)

    if shuffle:
        random.seed(seed)
        random.shuffle(rows)
    return rows


def write_csv(rows, out_path, append):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_header = not out_path.exists() or not append
    mode = "a" if append else "w"
    with out_path.open(mode, newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if write_header:
            writer.writerow(["text", "label"])
        writer.writerows(rows)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="data/train.csv")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--append",
        action="store_true",
        help="Append to existing CSV and avoid duplicates.",
    )
    parser.add_argument(
        "--shuffle",
        action="store_true",
        help="Shuffle rows before writing.",
    )
    args = parser.parse_args()

    out_path = Path(args.out)
    existing_texts = load_existing_texts(out_path) if args.append else set()
    rows = generate_samples(existing_texts, args.shuffle, args.seed)
    write_csv(rows, out_path, args.append)
    print(f"Wrote {len(rows)} rows to {args.out}")


if __name__ == "__main__":
    main()
